### ISSUE TITLE
Compilation fails in Scala 2.12.8 if one or more parameters have default values defined in the API trait

### ISSUE THREAD

**Issue by rpiaggio** [lihaoyi/autowire#78]
Example:

``` scala
trait SomeEntityApi {
  def retrieve(limit: Option[Int], skip: Int): Future[Seq[Entity]]
}
```

works, while:
``` scala
trait SomeEntityApi {
  def retrieve(limit: Option[Int] = None, skip: Int = 0): Future[Seq[Entity]]
}
```

fails with:
```
[warn] an unexpected type representation reached the compiler backend while compiling Application.scala: <error>. If possible, please file a bug on https://github.com/scala/bug/issues.
[error] Error while emitting Application.scala
[error] <error> (of class scala.reflect.internal.Types$ErrorType$)
[error] Error while emitting Application.scala
[error] assertion failed: ClassBType.info not yet assigned: Lcontrollers/Application$$anonfun$1;
[warn] one warning found
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
```

**Note 1**: What actually fails is the compilation of `Router.route[EventApi](new EventService)` (present in `Application.scala` in this case).

**Note 2**: Worked with Scala 2.12.6.

Thank you!

**Comment by urwithsumit** [comment]
Hi, 
I am having the same issue.
How were you able to work around on this issue?

thanks.

**Comment by Ahnfelt** [comment]
We get the same error on Scala 2.12.19. 
We can also reproduce the error on 2.12.8 but not on 2.12.7.
